# Setup
title: Makeng's blog
description: Nobody's code style is better than mine
url: https://makeng.github.io/blog
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg


# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
social:
  name: Zhaokeng Ma
  links:
    - https://github.com/makeng
    - https://www.zhihu.com/people/ma-zhao-keng
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Zhaokeng Ma
  url: https://github.com/makengg/
  email: 810768333@qq.com
